FROM node:carbon-alpine
ARG GIT_REPOSITORY=
ARG GIT_BRANCH_NAME=
ARG GIT_COMMIT_ID=
ARG ARTIFACT_VERSION=

ADD src/*.js* ./

RUN npm install

ENTRYPOINT [ "node", "index.js" ]

LABEL GIT_REPOSITORY=$GIT_REPOSITORY \
      GIT_BRANCH_NAME=$GIT_BRANCH_NAME \
      GIT_COMMIT_ID=$GIT_COMMIT_ID \
      ARTIFACT_VERSION=$ARTIFACT_VERSION